#Initialization of Tensors

In [2]:
from platform import python_version

In [2]:
print(python_version())

3.7.12


In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.7.0


In [7]:
x = tf.constant(4)
print(x)  # dtype is int32

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
x = tf.constant(4.0)
print(x)  # dtype is float32

tf.Tensor(4.0, shape=(), dtype=float32)


In [11]:
# with shape
x = tf.constant(4, shape=(1,1))
print(x)  # dtype is int32

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [14]:
# with shape & dtype

x = tf.constant(4, shape=(1,1), dtype=tf.float32)
# x = tf.constant(4, dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [16]:
# matrix definition

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(3,2))
print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [18]:
# matrix definition with auto initialization wih value 1's

x = tf.ones((3, 3), dtype=tf.int32)
print(x)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [20]:
# matrix definition with auto initialization wih value 0's

x = tf.zeros((3, 3), dtype=tf.float32)
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [21]:
# define identity matrix
x=tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [22]:
# define a matrix with normal distribution

x = tf.random.normal((3,3))
print(x)

tf.Tensor(
[[ 0.04224616 -1.3360387   0.9152105 ]
 [-0.06617372  1.3273189  -1.5369545 ]
 [-0.1570478  -1.1005961  -1.0322121 ]], shape=(3, 3), dtype=float32)


In [23]:
# define a matrix with uniform distribution

x = tf.random.uniform((1,3), minval=-1, maxval=1)
print(x)

tf.Tensor([[ 0.8446758 -0.5671792  0.5219853]], shape=(1, 3), dtype=float32)


In [24]:
# something similar the python range function

x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [25]:
# something similar the python range function

x = tf.range(delta=0.5, start=0, limit=10)
print(x)

tf.Tensor(
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5], shape=(20,), dtype=float32)


In [26]:
# casting the data type
x = tf.random.normal((3,3))
print(x)
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor(
[[-0.5527827   0.70623577 -1.5757234 ]
 [-1.4826794  -0.58726174 -1.5592871 ]
 [ 1.3977354  -0.9047918  -1.870166  ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.55278271  0.70623577 -1.57572341]
 [-1.48267937 -0.58726174 -1.55928707]
 [ 1.39773536 -0.90479177 -1.87016594]], shape=(3, 3), dtype=float64)


#Mathematical Operations

In [30]:
# Addition
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
print(tf.add(x, y))
print(x + y)


tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [31]:
# substraction
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
print(tf.subtract(y, x))
print(y - x)

tf.Tensor([8 6 4], shape=(3,), dtype=int32)
tf.Tensor([8 6 4], shape=(3,), dtype=int32)


In [32]:
# division
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
print(tf.divide(y, x))
print(y / x)

tf.Tensor([9.         4.         2.33333333], shape=(3,), dtype=float64)
tf.Tensor([9.         4.         2.33333333], shape=(3,), dtype=float64)


In [33]:
# multiplication
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])
print(tf.multiply(x, y))
print(x * y)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [37]:
# dot product

x = tf.constant([[1, 2, 3], [4, 5, 6]])
y = tf.constant([[9, 8, 7], [6, 5, 4]])
print(tf.tensordot(x, y, axes=0))

tf.Tensor(
[[[[ 9  8  7]
   [ 6  5  4]]

  [[18 16 14]
   [12 10  8]]

  [[27 24 21]
   [18 15 12]]]


 [[[36 32 28]
   [24 20 16]]

  [[45 40 35]
   [30 25 20]]

  [[54 48 42]
   [36 30 24]]]], shape=(2, 3, 2, 3), dtype=int32)


In [39]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
y = tf.constant([[9, 8, 7], [6, 5, 4]], shape=(3,2))
print(tf.tensordot(x, y, axes=1))

tf.Tensor(
[[ 38  32]
 [101  86]], shape=(2, 2), dtype=int32)


In [41]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
y = tf.constant([[9, 8, 7], [6, 5, 4]], shape=(2,3))
print(tf.reduce_sum(x * y, axis=0))

tf.Tensor([33 41 45], shape=(3,), dtype=int32)


In [43]:
x = tf.ones((1,3)) * 2
print(x ** 3)

tf.Tensor([[8. 8. 8.]], shape=(1, 3), dtype=float32)


In [44]:
# matrix mulitplication
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

print(tf.matmul(x, y))
print( x @ y)

tf.Tensor(
[[ 0.07761931  0.44154     0.29987833  0.05201834]
 [-1.3609456  -0.6347139  -0.27060086  0.94586515]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[ 0.07761931  0.44154     0.29987833  0.05201834]
 [-1.3609456  -0.6347139  -0.27060086  0.94586515]], shape=(2, 4), dtype=float32)


#Indexing

In [45]:
x = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[:])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [46]:
print(x[1:])

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [47]:
print(x[2:4])

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [48]:
print(x[::2])

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [49]:
print(x[::-1])

tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [50]:
indices = tf.constant([2, 6])
print(tf.gather(x, indices))

tf.Tensor([2 6], shape=(2,), dtype=int32)


In [24]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
print(x[:-1, :-1])

tf.Tensor(
[[1]
 [3]], shape=(2, 1), dtype=int32)
